// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comdef.proto

#ifndef PROTOBUF_comdef_2eproto__INCLUDED
#define PROTOBUF_comdef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace comdef {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_comdef_2eproto();
void protobuf_AssignDesc_comdef_2eproto();
void protobuf_ShutdownFile_comdef_2eproto();


enum cmd {
  msg_login = 1,
  msg_ss = 2,
  msg_base = 10,
  msg_role = 21,
  msg_friend = 22,
  msg_room = 23,
  msg_rank = 24,
  msg_broadcast = 25,
  msg_shop = 26,
  msg_mail = 27,
  msg_activity = 28,
  msg_achieve = 29,
  msg_event = 30,
  msg_maj = 31,
  msg_test = 32,
  msg_hist = 33,
  msg_gm = 34
};
bool cmd_IsValid(int value);
const cmd cmd_MIN = msg_login;
const cmd cmd_MAX = msg_gm;
const int cmd_ARRAYSIZE = cmd_MAX + 1;

const ::google::protobuf::EnumDescriptor* cmd_descriptor();
inline const ::std::string& cmd_Name(cmd value) {
  return ::google::protobuf::internal::NameOfEnum(
    cmd_descriptor(), value);
}
inline bool cmd_Parse(
    const ::std::string& name, cmd* value) {
  return ::google::protobuf::internal::ParseNamedEnum<cmd>(
    cmd_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace comdef

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::comdef::cmd> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::comdef::cmd>() {
  return ::comdef::cmd_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_comdef_2eproto__INCLUDED
