// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sorlists.proto

#ifndef PROTOBUF_sorlists_2eproto__INCLUDED
#define PROTOBUF_sorlists_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_sorlists_2eproto();
void protobuf_AssignDesc_sorlists_2eproto();
void protobuf_ShutdownFile_sorlists_2eproto();

class LevelBinary;
class LevelRow;
class LevelTable;

// ===================================================================

class LevelBinary : public ::google::protobuf::Message {
 public:
  LevelBinary();
  virtual ~LevelBinary();

  LevelBinary(const LevelBinary& from);

  inline LevelBinary& operator=(const LevelBinary& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LevelBinary& default_instance();

  void Swap(LevelBinary* other);

  // implements Message ----------------------------------------------

  inline LevelBinary* New() const { return New(NULL); }

  LevelBinary* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LevelBinary& from);
  void MergeFrom(const LevelBinary& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LevelBinary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 other = 1;
  bool has_other() const;
  void clear_other();
  static const int kOtherFieldNumber = 1;
  ::google::protobuf::int32 other() const;
  void set_other(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf.LevelBinary)
 private:
  inline void set_has_other();
  inline void clear_has_other();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 other_;
  friend void  protobuf_AddDesc_sorlists_2eproto();
  friend void protobuf_AssignDesc_sorlists_2eproto();
  friend void protobuf_ShutdownFile_sorlists_2eproto();

  void InitAsDefaultInstance();
  static LevelBinary* default_instance_;
};
// -------------------------------------------------------------------

class LevelRow : public ::google::protobuf::Message {
 public:
  LevelRow();
  virtual ~LevelRow();

  LevelRow(const LevelRow& from);

  inline LevelRow& operator=(const LevelRow& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LevelRow& default_instance();

  void Swap(LevelRow* other);

  // implements Message ----------------------------------------------

  inline LevelRow* New() const { return New(NULL); }

  LevelRow* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LevelRow& from);
  void MergeFrom(const LevelRow& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LevelRow* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sortid = 1;
  bool has_sortid() const;
  void clear_sortid();
  static const int kSortidFieldNumber = 1;
  ::google::protobuf::int32 sortid() const;
  void set_sortid(::google::protobuf::int32 value);

  // optional int64 uid = 2;
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::int64 uid() const;
  void set_uid(::google::protobuf::int64 value);

  // optional string name = 3;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 level = 4;
  bool has_level() const;
  void clear_level();
  static const int kLevelFieldNumber = 4;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // optional .protobuf.LevelBinary binData = 5;
  bool has_bindata() const;
  void clear_bindata();
  static const int kBinDataFieldNumber = 5;
  const ::protobuf::LevelBinary& bindata() const;
  ::protobuf::LevelBinary* mutable_bindata();
  ::protobuf::LevelBinary* release_bindata();
  void set_allocated_bindata(::protobuf::LevelBinary* bindata);

  // @@protoc_insertion_point(class_scope:protobuf.LevelRow)
 private:
  inline void set_has_sortid();
  inline void clear_has_sortid();
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_bindata();
  inline void clear_has_bindata();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 uid_;
  ::google::protobuf::int32 sortid_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::protobuf::LevelBinary* bindata_;
  friend void  protobuf_AddDesc_sorlists_2eproto();
  friend void protobuf_AssignDesc_sorlists_2eproto();
  friend void protobuf_ShutdownFile_sorlists_2eproto();

  void InitAsDefaultInstance();
  static LevelRow* default_instance_;
};
// -------------------------------------------------------------------

class LevelTable : public ::google::protobuf::Message {
 public:
  LevelTable();
  virtual ~LevelTable();

  LevelTable(const LevelTable& from);

  inline LevelTable& operator=(const LevelTable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LevelTable& default_instance();

  void Swap(LevelTable* other);

  // implements Message ----------------------------------------------

  inline LevelTable* New() const { return New(NULL); }

  LevelTable* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LevelTable& from);
  void MergeFrom(const LevelTable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LevelTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 itemid = 1;
  bool has_itemid() const;
  void clear_itemid();
  static const int kItemidFieldNumber = 1;
  ::google::protobuf::int32 itemid() const;
  void set_itemid(::google::protobuf::int32 value);

  // repeated .protobuf.LevelRow levels = 2;
  int levels_size() const;
  void clear_levels();
  static const int kLevelsFieldNumber = 2;
  const ::protobuf::LevelRow& levels(int index) const;
  ::protobuf::LevelRow* mutable_levels(int index);
  ::protobuf::LevelRow* add_levels();
  ::google::protobuf::RepeatedPtrField< ::protobuf::LevelRow >*
      mutable_levels();
  const ::google::protobuf::RepeatedPtrField< ::protobuf::LevelRow >&
      levels() const;

  // @@protoc_insertion_point(class_scope:protobuf.LevelTable)
 private:
  inline void set_has_itemid();
  inline void clear_has_itemid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::protobuf::LevelRow > levels_;
  ::google::protobuf::int32 itemid_;
  friend void  protobuf_AddDesc_sorlists_2eproto();
  friend void protobuf_AssignDesc_sorlists_2eproto();
  friend void protobuf_ShutdownFile_sorlists_2eproto();

  void InitAsDefaultInstance();
  static LevelTable* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LevelBinary

// optional int32 other = 1;
inline bool LevelBinary::has_other() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LevelBinary::set_has_other() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LevelBinary::clear_has_other() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LevelBinary::clear_other() {
  other_ = 0;
  clear_has_other();
}
inline ::google::protobuf::int32 LevelBinary::other() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelBinary.other)
  return other_;
}
inline void LevelBinary::set_other(::google::protobuf::int32 value) {
  set_has_other();
  other_ = value;
  // @@protoc_insertion_point(field_set:protobuf.LevelBinary.other)
}

// -------------------------------------------------------------------

// LevelRow

// optional int32 sortid = 1;
inline bool LevelRow::has_sortid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LevelRow::set_has_sortid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LevelRow::clear_has_sortid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LevelRow::clear_sortid() {
  sortid_ = 0;
  clear_has_sortid();
}
inline ::google::protobuf::int32 LevelRow::sortid() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelRow.sortid)
  return sortid_;
}
inline void LevelRow::set_sortid(::google::protobuf::int32 value) {
  set_has_sortid();
  sortid_ = value;
  // @@protoc_insertion_point(field_set:protobuf.LevelRow.sortid)
}

// optional int64 uid = 2;
inline bool LevelRow::has_uid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LevelRow::set_has_uid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LevelRow::clear_has_uid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LevelRow::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::int64 LevelRow::uid() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelRow.uid)
  return uid_;
}
inline void LevelRow::set_uid(::google::protobuf::int64 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:protobuf.LevelRow.uid)
}

// optional string name = 3;
inline bool LevelRow::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LevelRow::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LevelRow::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LevelRow::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& LevelRow::name() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelRow.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LevelRow::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protobuf.LevelRow.name)
}
inline void LevelRow::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protobuf.LevelRow.name)
}
inline void LevelRow::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protobuf.LevelRow.name)
}
inline ::std::string* LevelRow::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:protobuf.LevelRow.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LevelRow::release_name() {
  // @@protoc_insertion_point(field_release:protobuf.LevelRow.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LevelRow::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:protobuf.LevelRow.name)
}

// optional int32 level = 4;
inline bool LevelRow::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LevelRow::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LevelRow::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LevelRow::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 LevelRow::level() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelRow.level)
  return level_;
}
inline void LevelRow::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:protobuf.LevelRow.level)
}

// optional .protobuf.LevelBinary binData = 5;
inline bool LevelRow::has_bindata() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LevelRow::set_has_bindata() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LevelRow::clear_has_bindata() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LevelRow::clear_bindata() {
  if (bindata_ != NULL) bindata_->::protobuf::LevelBinary::Clear();
  clear_has_bindata();
}
inline const ::protobuf::LevelBinary& LevelRow::bindata() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelRow.binData)
  return bindata_ != NULL ? *bindata_ : *default_instance_->bindata_;
}
inline ::protobuf::LevelBinary* LevelRow::mutable_bindata() {
  set_has_bindata();
  if (bindata_ == NULL) {
    bindata_ = new ::protobuf::LevelBinary;
  }
  // @@protoc_insertion_point(field_mutable:protobuf.LevelRow.binData)
  return bindata_;
}
inline ::protobuf::LevelBinary* LevelRow::release_bindata() {
  // @@protoc_insertion_point(field_release:protobuf.LevelRow.binData)
  clear_has_bindata();
  ::protobuf::LevelBinary* temp = bindata_;
  bindata_ = NULL;
  return temp;
}
inline void LevelRow::set_allocated_bindata(::protobuf::LevelBinary* bindata) {
  delete bindata_;
  bindata_ = bindata;
  if (bindata) {
    set_has_bindata();
  } else {
    clear_has_bindata();
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.LevelRow.binData)
}

// -------------------------------------------------------------------

// LevelTable

// optional int32 itemid = 1;
inline bool LevelTable::has_itemid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LevelTable::set_has_itemid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LevelTable::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LevelTable::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 LevelTable::itemid() const {
  // @@protoc_insertion_point(field_get:protobuf.LevelTable.itemid)
  return itemid_;
}
inline void LevelTable::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
  // @@protoc_insertion_point(field_set:protobuf.LevelTable.itemid)
}

// repeated .protobuf.LevelRow levels = 2;
inline int LevelTable::levels_size() const {
  return levels_.size();
}
inline void LevelTable::clear_levels() {
  levels_.Clear();
}
inline const ::protobuf::LevelRow& LevelTable::levels(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.LevelTable.levels)
  return levels_.Get(index);
}
inline ::protobuf::LevelRow* LevelTable::mutable_levels(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.LevelTable.levels)
  return levels_.Mutable(index);
}
inline ::protobuf::LevelRow* LevelTable::add_levels() {
  // @@protoc_insertion_point(field_add:protobuf.LevelTable.levels)
  return levels_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::protobuf::LevelRow >*
LevelTable::mutable_levels() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.LevelTable.levels)
  return &levels_;
}
inline const ::google::protobuf::RepeatedPtrField< ::protobuf::LevelRow >&
LevelTable::levels() const {
  // @@protoc_insertion_point(field_list:protobuf.LevelTable.levels)
  return levels_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sorlists_2eproto__INCLUDED
